# Generated by Django 2.2 on 2020-03-29 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_is_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
