# Generated by Django 2.2 on 2020-03-28 13:06

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DateClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('dateclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.DateClass')),
                ('category_name', models.CharField(choices=[('athletic', 'athletic'), ('educational', 'educational'), ('scientific', 'scientific'), ('political', 'political'), ('cultural', 'cultural'), ('historical', 'historical')], max_length=50)),
            ],
            bases=('content.dateclass',),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('dateclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.DateClass')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', related_query_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('content.dateclass',),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('dateclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.DateClass')),
                ('amount', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('store_subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='content.Store')),
            ],
            bases=('content.dateclass',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('dateclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.DateClass')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.PositiveIntegerField(blank=True, null=True)),
                ('is_free', models.BooleanField()),
                ('product_category', models.ManyToManyField(related_name='products_category', related_query_name='product_category', to='content.Category')),
                ('product_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_store', related_query_name='product_store', to='content.Store')),
            ],
            bases=('content.dateclass',),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('dateclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.DateClass')),
                ('file_name', models.CharField(blank=True, max_length=30, null=True)),
                ('file_data', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'avi', 'flv', 'wmv', 'mov', 'mp4', 'wma', 'flac', 'aac', 'mp3'])])),
                ('file_price', models.PositiveIntegerField(blank=True, null=True)),
                ('is_free', models.BooleanField()),
                ('file_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_products', related_query_name='file_product', to='content.Product', verbose_name='belonges_to_this_product')),
            ],
            bases=('content.dateclass',),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('dateclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.DateClass')),
                ('baught_products', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None)),
                ('baught_files', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None)),
                ('baught_subscriptions', models.ManyToManyField(related_name='carts', related_query_name='cart', to='content.Subscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_carts', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('content.dateclass',),
        ),
    ]
