# Generated by Django 2.2 on 2020-03-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='buy_confirmation',
            field=models.CharField(choices=[('buy', 'buy'), ('cancel', 'cancel')], default='cancel', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='buy_confirmation',
            field=models.CharField(choices=[('buy', 'buy'), ('cancel', 'cancel')], default='cancel', max_length=20),
        ),
    ]
