# Generated by Django 2.2 on 2020-03-28 21:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200328_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='baught_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='cart',
            name='baught_products',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='cart',
            name='baught_subscriptions',
            field=models.ManyToManyField(blank=True, null=True, related_name='carts', related_query_name='cart', to='content.Subscription'),
        ),
    ]
