# Generated by Django 2.2 on 2020-03-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200328_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='buy_confirmation',
            field=models.CharField(choices=[('buy', 'buy'), ('cancel', 'cancel')], default='cancel', max_length=20),
        ),
        migrations.AlterField(
            model_name='cart',
            name='baught_subscriptions',
            field=models.ManyToManyField(related_name='carts', related_query_name='cart', to='content.Subscription'),
        ),
    ]
