# Generated by Django 2.2 on 2020-03-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20200328_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='cart',
            name='date_of_buying_subscription',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='expiry_date_amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='expiry_date_unit',
            field=models.CharField(choices=[('day', 'day'), ('month', 'month'), ('year', 'year')], default='day', max_length=20),
            preserve_default=False,
        ),
    ]
