# Generated by Django 2.2 on 2020-03-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20200329_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiry_date_unit',
            field=models.CharField(choices=[('day', 'day'), ('hour', 'hour')], max_length=20),
        ),
    ]
